import type { Metadata } from "next";
import localFont from 'next/font/local'

import "./globals.css";

const space_mono = localFont({
  src: './SpaceMono-Bold.woff2',
  display: 'swap',
  variable: '--ff-space-mono'
});

export const metadata: Metadata = {
  title: "Frontend Mentor | Tip calculator app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={space_mono.className}>{children}</body>
    </html>
  );
}
